import {useRef,useEffect,useLayoutEffect} from 'react'
const useBrowserLayoutEffect=typeof window==='undefined'?useEffect:useLayoutEffect
import type {BeatNex} from '../../features/useBeatNex'
import {DRUM_IDS} from '../../core/pattern/types'
import {meterForPattern} from '../../core/pattern/editor'
import {PHASE_GUIDES,phaseIds} from '../../storage/practice'
import {TempoWheel} from '../components/TempoWheel'
import {DrumIcon,Icon,drumNames,labelDrums} from '../components/Icons'
import {PhaseChipEditor} from '../PhaseChipEditor'
import {usePadVolume} from '../usePadVolume'
import {PracticeProgress} from '../components/PracticeProgress'
export function PracticePage({app}:{app:BeatNex}){
 const {settings,selectedDrums,pattern,snapshot,playing,loading,phases,activeIndex,cycle,totalBars}=app
 const mode=settings.routeEnabled?'route':'free'
 const volumeGesture=usePadVolume(!settings.routeEnabled&&app.page==='practice',settings.freeVolumes,app.changeFreeVolume)
 const padsLocked=settings.routeEnabled&&(playing||loading)
 const volumeLabels={normal:'正常音量',weak:'弱化音量',silent:'静音'}
 const beats=useRef<HTMLDivElement>(null),marker=useRef<HTMLSpanElement>(null)
 const lastTap=useRef({key:'',at:0})
 const freeTime=Math.floor(snapshot.elapsed/60).toString().padStart(2,'0')+':'+Math.floor(snapshot.elapsed%60).toString().padStart(2,'0')
 const pulse=Math.floor((snapshot.progress*(snapshot.isCountIn?1:pattern.bars)%1)*pattern.beatsPerBar*2),guide=PHASE_GUIDES[phaseIds.indexOf(phases[activeIndex].id as never)].replace('{drum}',labelDrums(settings.targets))
 useBrowserLayoutEffect(()=>{const root=beats.current,node=marker.current;if(!root||!node)return;const place=()=>{const cell=root.querySelectorAll<HTMLElement>('.bn-count')[pulse];if(!cell)return;const a=root.getBoundingClientRect(),b=cell.getBoundingClientRect();Object.assign(node.style,{width:b.width+'px',height:b.height+'px',transform:`translate(${b.left-a.left}px,${b.top-a.top}px)`,background:pulse%2?'var(--lilac)':'var(--acid)'});};place();const observer=new ResizeObserver(place);observer.observe(root);return()=>observer.disconnect()},[pulse,pattern.beatsPerBar,app.page])
 return <section className="bn-page" data-view="practice" hidden={app.page!=='practice'}><div className="bn-layout"><article className="bn-card bn-session"><div><div className="bn-row"><span className="bn-tag">{app.activeId?'我的组合':'BOOM BAP / HIP-HOP'}</span><span className="bn-live"><i className="bn-dot"/><span id="bn-status">{loading?'正在加载鼓组':snapshot.isCountIn?'预备拍':playing?'正在练习':snapshot.status==='paused'?'已暂停':'准备就绪'}</span></span></div><h2 id="bn-pattern-title">{pattern.name}</h2><div className="bn-sub"><span id="bn-current-drum">鼓组练习</span><span id="bn-practice-meter">{meterForPattern(pattern)}</span><span className="bn-duration-slot"><span id="bn-duration">约 {Math.round(totalBars*60*pattern.beatsPerBar*4/(pattern.beatUnit??4)/settings.bpm)} 秒</span><span id="bn-free-session" hidden={settings.routeEnabled}>已练习 <b id="bn-free-time">{freeTime}</b></span></span></div></div><div><div ref={beats} className="bn-beats" aria-label={meterForPattern(pattern)+' 节拍提示'} style={{gridTemplateColumns:`repeat(${Math.min(6,pattern.beatsPerBar)},minmax(0,1fr))`}}><span ref={marker} className="bn-count-marker" aria-hidden="true"/>{Array.from({length:pattern.beatsPerBar},(_,i)=><div className={'bn-beat '+(playing&&Math.floor(pulse/2)===i?'on':'')} key={i}><b className={'bn-count '+(playing&&pulse===i*2?'is-current':'')}>{i+1}</b><span className={'bn-count bn-and '+(playing&&pulse===i*2+1?'is-current':'')}>&amp;</span></div>)}</div><div className="bn-row"><button className="bn-primary" id="bn-play" onClick={app.togglePlayback} disabled={loading}><Icon name={playing?'pause':'play'}/><span>{loading?'加载中…':playing?'暂停练习':snapshot.status==='paused'?'继续练习':'开始练习'}</span></button><button id="bn-free-end" aria-label="结束自由练习" onClick={app.endFree}>结束</button><button className="bn-smallbtn" id="bn-reset" aria-label="重新开始练习" onClick={()=>{app.reset();app.notice('已回到练习起点')}}><Icon name="reset"/></button></div></div><div className="bn-in-player bn-player-tempo"><article className="bn-card bn-tempo"><TempoWheel value={settings.bpm} min={60} max={140} onChange={app.changeBpm} label="练习速度"/><div className="bn-row bn-muted"><span>60 · 慢慢来</span><span>140 · 加点速</span></div></article></div></article>
 <article className="bn-card bn-mode-panel" data-mode={mode} aria-label="练习模式与设置">
 <div className="bn-practice-modes" role="group" aria-label="练习模式">{(['free','route'] as const).map(next=><button key={next} type="button" aria-pressed={mode===next} onClick={()=>app.changeMode(next)}>{next==='free'?'自由练习':'路线练习'}</button>)}</div>
 <div className="bn-mode-content">
 <div className="bn-target-heading"><h3>{settings.routeEnabled?'练习目标':'播放鼓件'}</h3></div>
 <p className="bn-mode-help">{settings.routeEnabled?(padsLocked?'路线自动控制鼓件，暂停后可调整目标。':'路线决定目标鼓件何时独奏、弱化或静音。'):'长按鼓垫后上下拖动，调节单鼓音量。'}</p>
 <div className="bn-instruments"><div className="bn-drums" id="bn-drums" aria-describedby="bn-drum-help">{DRUM_IDS.map((drum,i)=><button className="bn-drum" key={drum} data-drum={i} data-free={!settings.routeEnabled} data-adjusting={volumeGesture.adjusting===drum} onPointerDown={e=>volumeGesture.onPointerDown(drum,e)} onPointerMove={volumeGesture.onPointerMove} onPointerUp={volumeGesture.onPointerEnd} onPointerCancel={volumeGesture.onPointerEnd} onLostPointerCapture={volumeGesture.onPointerEnd} onContextMenu={e=>{if(!settings.routeEnabled)e.preventDefault()}} disabled={padsLocked} data-level={playing?(snapshot.drums?.[drum]?.level??'silent'):'idle'} data-hit={playing&&!!snapshot.drums?.[drum]?.hit} aria-label={drumNames[i]+(!settings.routeEnabled?'，音量 '+(settings.freeVolumes?.[drum]??100)+'%':'')+(playing?'，'+volumeLabels[snapshot.drums?.[drum]?.level??'silent']:'')+(selectedDrums.includes(drum)?settings.routeEnabled?'，目标鼓件':'，已选择':'')+(padsLocked?'，已锁定':'')} aria-pressed={selectedDrums.includes(drum)} onClick={e=>{if(volumeGesture.consumeClick()){lastTap.current={key:'',at:0};return}const now=performance.now(),double=e.detail>=2||(e.detail!==0&&lastTap.current.key===drum&&now-lastTap.current.at<340);lastTap.current={key:double?'':drum,at:now};app.selectDrum(drum,double)}} onKeyDown={e=>{if(!settings.routeEnabled&&['ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();app.changeFreeVolume(drum,e.key==='Home'?0:e.key==='End'?100:(settings.freeVolumes?.[drum]??100)+(e.key==='ArrowUp'?5:-5));return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();app.selectDrum(drum,true)}}}><DrumIcon index={i}/><span>{drumNames[i]}</span>{padsLocked&&<span className="bn-pad-lock" aria-hidden="true"><svg viewBox="0 0 16 16"><rect x="3" y="7" width="10" height="7" rx="2"/><path d="M5 7V5a3 3 0 0 1 6 0v2"/></svg></span>}<span className="bn-pad-volume" aria-hidden="true"><i style={!settings.routeEnabled?{transform:`scaleX(${(settings.freeVolumes?.[drum]??100)/100})`}:undefined}/></span>{!settings.routeEnabled&&<span className="bn-pad-percent" aria-hidden="true">{settings.freeVolumes?.[drum]??100}%</span>}</button>)}</div><div id="bn-drum-help">{volumeGesture.adjusting?<span>上下拖动调音量 · 松手完成</span>:playing?<span className="bn-volume-key" aria-label="鼓垫音量图例"><span data-level="normal"><i/>{settings.routeEnabled?'正常':'播放'}</span>{settings.routeEnabled&&<span data-level="weak"><i/>弱化</span>}<span data-level="silent"><i/>静音</span></span>:padsLocked?'路线控制音量 · 暂停后可调整目标':settings.routeEnabled?'单击选择 · 双击取消':'点选 · 双击取消 · 长按上下调音量'}</div></div>
 {settings.routeEnabled?<>
 <PracticeProgress total={totalBars} cycle={cycle} snapshot={snapshot} complete={app.completed} round={app.round} infinite={settings.repeat==='infinite'} enabled phaseLabel={phases[activeIndex].label} guide={settings.targets.length?guide:'点选需要的目标鼓件；双击可取消选择'}/>
 <div className="bn-course" aria-label="练习路线编排"><div className="bn-row"><div><h3>路线阶段</h3><span className="bn-muted" id="bn-route-hint">长按拖动 · 拖入垃圾桶删除</span></div><div className="bn-repeat-control" role="group" aria-label="路线循环模式"><i aria-hidden="true" style={{transform:`translateX(${settings.repeat==='infinite'?100:0}%)`}}/>{(['once','infinite'] as const).map(mode=><button key={mode} type="button" aria-label={mode==='once'?'循环一次':'无限循环'} title={mode==='once'?'循环一次':'无限循环'} aria-pressed={settings.repeat===mode} disabled={playing||loading} onClick={()=>app.changeRepeat(mode)}>{mode==='once'?'1×':'∞'}</button>)}</div></div><PhaseChipEditor phases={phases} locked={playing||loading||app.page!=='practice'} activeIndex={activeIndex} onBarsChange={app.changeBars} onReorder={app.reorder} onDelete={app.removePhase} onAdd={app.addPhase} notice={app.notice} onPreview={app.phasePreview.toggle} previewKey={app.phasePreview.key} previewPlaying={app.phasePreview.loading||app.phasePreview.snapshot.status==='playing'}/></div>
 {app.phasePreview.snapshot.error&&<p role="alert">阶段试听失败：{app.phasePreview.snapshot.error}，点击试听重试。</p>}
 </>:null}
 </div></article></div></section>
}
